layout_spectrum: 0.7726458753459156
name: radical change
typography_spectrum: 0.005882357712835073
color:
  brandStrength: 0.1322264589834958
  saturation: 0.9355348106473684
  brandColors:
    - '#A50000'
    - '#FFFFFF'
    - '#3B5998'
    - '#000000'
    - '#0096C1'
  lightness: 0.8814832414500415
  rhythmicContrast: 0.8775479346513748
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
